## Customize the test machine
language: python

python:
  - 3.6.3

addons:
  - postgresql: "9.5"

before_install:
  - export DEBUG=False
  - export DABATASE_URL=postgres://postgres@localhost/travisdb

install:
  - pip install -r requirements.txt

#before_script:
#  - psql -c "CREATE DATABASE travisdb;" -U postgres
#  - python learn_resources/manage.py migrate --noinput

env:
  - DJANGO=1.11

script: python manage.py test