## Customize the test machine
language: python

python:
  - 3.6.3

addons:
  - postgresql: "9.5"

before_install:
  - export DEBUG=False
  - export DATABASE_URL=postgres://postgres@localhost/travisdb

install:
  - pip install -r requirements.txt

env:
  - DJANGO=1.11

script: python manage.py test --settings=tst

cache: pip
